function motorRAWmaterials = calculateLCAImpacts(motorRAWmaterials)
% CALCULATELCAIMPACTS Calculate normalized impacts and unique score for motor materials
%
% Syntax:
%   motorRAWmaterials = calculateLCAImpacts(motorRAWmaterials)
%
% Input:
%   motorRAWmaterials - Structure array containing material properties and
%                       environmental impacts (from importMotorMaterialsCSV)
%
% Output:
%   motorRAWmaterials - Updated structure with normalized impacts and unique score
%                       for each material
%
% The function:
%   1. Applies Normalization Factors (NF) from EF v3.1 method
%   2. Calculates Weighting Factors (WF)
%   3. Computes normalized impact for each EF category
%   4. Calculates unique score (single score) for each material
%
% Authors: Hugo HELBLING <hugo.helbling@univ-lyon1.fr>
%          Romain DELPOUX <romain.delpoux@insa-lyon.fr>
%          Maîtres de Conférences, Laboratoire Ampere
% Date: March 2026

    % Define Normalization Factors (NF) for EF v3.1 impact categories
    % Values from European reference scenario
    % Names match those generated by importMotorMaterialsCSV
    NF = struct();

    NF.Acidification = 55.6;
    NF.ClimateChange = 7550;
    NF.EcotoxicityFreshwater = 56700;
    NF.ParticulateMatterFormation = 5.95E-04;
    NF.EutrophicationFreshwater = 1.61;
    NF.EutrophicationMarine = 19.5;
    NF.EutrophicationTerrestrial = 177;
    NF.HumanToxicityCarcinogenic = 1.73E-05;
    NF.HumanToxicityNoncarcinogenic = 1.29E-04;
    NF.IonisingRadiationHumanHealth = 4220;
    NF.LandUse = 819000;
    NF.OzoneDepletion = 0.0523;
    NF.PhotochemicalOxidantFormationHumanHealth = 40.9;
    NF.EnergyResourcesNonrenewable = 65000;
    NF.MaterialResourcesMetalsminerals = 0.0636;
    NF.WaterUse = 11500;

    % Define Weighting Factors (WF) for EF v3.1
    % Values from official EF v3.1 methodology
    WF = struct();

    WF.Acidification = 6.2;
    WF.ClimateChange = 21.06;
    WF.EcotoxicityFreshwater = 1.92;
    WF.ParticulateMatterFormation = 8.96;
    WF.EutrophicationFreshwater = 2.8;
    WF.EutrophicationMarine = 2.96;
    WF.EutrophicationTerrestrial = 3.71;
    WF.HumanToxicityCarcinogenic = 2.13;
    WF.HumanToxicityNoncarcinogenic = 1.84;
    WF.IonisingRadiationHumanHealth = 5.01;
    WF.LandUse = 7.94;
    WF.OzoneDepletion = 6.31;
    WF.PhotochemicalOxidantFormationHumanHealth = 4.78;
    WF.EnergyResourcesNonrenewable = 8.32;
    WF.MaterialResourcesMetalsminerals = 7.55;
    WF.WaterUse = 8.51;

    % Get impact category names
    impactCategories = fieldnames(NF);

    % Process each material
    for i = 1:length(motorRAWmaterials)
        uniqueScore = 0;
        normalizedImpacts = struct();

        % Calculate normalized impact for each category
        for j = 1:length(impactCategories)
            categoryName = impactCategories{j};

            % Check if this impact category exists in the material data
            if isfield(motorRAWmaterials(i), categoryName)
                rawImpact = motorRAWmaterials(i).(categoryName);

                % Handle non-numeric values
                if isnumeric(rawImpact)
                    % Normalized Impact = Raw Impact / NF
                    normalizedImpact = rawImpact / NF.(categoryName);

                    % Weighted Impact = Normalized Impact * WF
                    weightedImpact = normalizedImpact * WF.(categoryName) / 100;

                    % Store normalized impact
                    normalizedImpacts.(categoryName) = normalizedImpact;

                    % Add to unique score
                    uniqueScore = uniqueScore + weightedImpact;
                else
                    normalizedImpacts.(categoryName) = NaN;
                end
            else
                normalizedImpacts.(categoryName) = NaN;
            end
        end

        % Add normalized impacts to the structure
        motorRAWmaterials(i).NormalizedImpacts = normalizedImpacts;

        % Add unique score to the structure
        motorRAWmaterials(i).UniqueScore = uniqueScore;
    end

    fprintf('Successfully calculated LCA impacts for %d materials.\n', length(motorRAWmaterials));

end
